# Flujo de trabajo simple para desplegar contenido estático a GitHub Pages
name: Deploy GeoAlertAR Demo to Pages

on:
  # Se ejecuta en pushes a la rama `main`
  push:
    branches: ["main"]

  # Permite ejecutarlo manualmente desde la pestaña Actions
  workflow_dispatch:

# Permisos necesarios para el despliegue
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Tarea única de despliegue
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Pages
        uses: actions/configure-pages@v5
      
      - name: Upload artifact from webapp folder
        uses: actions/upload-pages-artifact@v3
        with:
          # Aquí está la clave: le decimos que suba el contenido de la carpeta 'webapp'
          path: './webapp'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4